name: create_pypi_package

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_publish_package:
    name: Build and publish the PyPi package
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Bump package version
        run: bump2version --current-version $(cat VERSION) patch VERSION

      - name: Checkout submodules using a PAT
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.OPENDATADISCOVERY_BOT_PAT }}:${{ secrets.OPENDATADISCOVERY_BOT_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
          git submodule foreach git pull origin main
          git checkout .gitmodules

      - name: Set ODD_CONTRACT_VERSION environment variable
        run: echo "ODD_CONTRACT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Run docker build
        run: |
          docker build . -t ignored \
            --build-arg ODD_CONTRACT_VERSION=${{ env.ODD_CONTRACT_VERSION }} \
            --build-arg TWINE_USERNAME=${{ secrets.PYPI_USERNAME }} \
            --build-arg TWINE_PASSWORD=${{ secrets.PYPI_PASSWORD }} 

      - name: Update repository with up-to-date submodules and version
        run: |
          git config --global user.email "opendatadiscovery-bot@provectus.com"
          git config --global user.name "OpenDataDiscovery Bot"
          if [ -n "$(git status --porcelain)" ]
          then
            git add .
            git commit -m "Update submodule branch ref and bump package version"
            git push origin main
          fi
